[export]
OutputDirectory = "./exported/"

[forum]
Product = "vBulletin"
MajorVersion = 3
MinorVersion = 8

[database]
Server       = "127.0.0.1"
Port         = 3306
Database     = "lfgss"
Username     = "root"
Password     = "root"
TablePrefix  = "vb_"
